---
volumes:
  prometheus-data:
    driver: local
  grafana-data:
      driver: local
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  grafana:
    image: docker.io/grafana/grafana-oss:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  app:
    image: node:20
    volumes:
      - .:/app
    ports:
      - 3010:3010
    working_dir: /app
    command: npm start

networks:
  default:
    driver: bridge